name: Publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
      - name: Install wasi-vfs
        run: |
          wasi_vfs_cli_url="https://github.com/kateinoigakukun/wasi-vfs/releases/download/v${WASI_VFS_VERSION}/wasi-vfs-cli-x86_64-unknown-linux-gnu.zip"
          curl -LO "$wasi_vfs_cli_url"
          unzip wasi-vfs-cli-x86_64-unknown-linux-gnu.zip
          mv wasi-vfs /usr/local/bin/wasi-vfs
        env:
          WASI_VFS_VERSION: "0.1.0"
      - name: Build repl.wasm
        run: make static/repl.wasm
      - name: Bundle web resources
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist